# This file was generated by GoReleaser. DO NOT EDIT.
cask "docker-top" do
  name "docker-top"
  desc "docker-top - A TUI for monitoring Docker Compose projects."
  homepage "https://github.com/Fuabioo/docker-top"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docker-top"

  on_macos do
    on_intel do
      url "https://github.com/Fuabioo/docker-top/releases/download/v#{version}/docker-top_Darwin_amd64.tar.gz"
      sha256 "014d2e331b4d90d5526ad0009dfa98c6ec8d69acd2e29e347dd53daae7320eb2"
    end
    on_arm do
      url "https://github.com/Fuabioo/docker-top/releases/download/v#{version}/docker-top_Darwin_arm64.tar.gz"
      sha256 "c55e8d9fa47970510cc62bc2b57cf39acbd0da4e8fd9a1504a3a182cb1aa82d8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Fuabioo/docker-top/releases/download/v#{version}/docker-top_Linux_amd64.tar.gz"
      sha256 "c56d6d536d8e983de9a24a42224ce119e0737302040088063957af45a9e203b7"
    end
    on_arm do
      url "https://github.com/Fuabioo/docker-top/releases/download/v#{version}/docker-top_Linux_arm64.tar.gz"
      sha256 "fe1f69613651a65fe13fee42753bbe1ec7a3f952cb4c13165fb3c1e683c24c92"
    end
  end

  # No zap stanza required
end
