# This file was generated by GoReleaser. DO NOT EDIT.
cask "docker-top" do
  name "docker-top"
  desc "docker-top - A TUI for monitoring Docker Compose projects."
  homepage "https://github.com/Fuabioo/docker-top"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docker-top"

  on_macos do
    on_intel do
      url "https://github.com/Fuabioo/docker-top/releases/download/v#{version}/docker-top_Darwin_amd64.tar.gz"
      sha256 "9dd37ff84f5c2316c0c24d6f59c44f4549e83503fb00379a86b8002342b124e6"
    end
    on_arm do
      url "https://github.com/Fuabioo/docker-top/releases/download/v#{version}/docker-top_Darwin_arm64.tar.gz"
      sha256 "688a26d98228ce1d77c70fac288b05db2473ec176332dfb6cbb506f54c3ab68a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Fuabioo/docker-top/releases/download/v#{version}/docker-top_Linux_amd64.tar.gz"
      sha256 "7e648621e9aa37e29f7f3fc93efb30490001aeba06b18e0c9bedbbb0f4e2564b"
    end
    on_arm do
      url "https://github.com/Fuabioo/docker-top/releases/download/v#{version}/docker-top_Linux_arm64.tar.gz"
      sha256 "4b8a4df13084d8b284cefde3e4306e141f5f80daf4d2b8805112b615a8a62652"
    end
  end

  # No zap stanza required
end
