# This file was generated by GoReleaser. DO NOT EDIT.
cask "user-top" do
  name "user-top"
  desc "user-top - A TUI for monitoring active user sessions across Linux nodes."
  homepage "https://github.com/Fuabioo/user-top"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "user-top"

  on_macos do
    on_intel do
      url "https://github.com/Fuabioo/user-top/releases/download/v#{version}/user-top_Darwin_amd64.tar.gz"
      sha256 "76247578cebc59e2753f63d35cc75893af0b8f197c671477fd030152d37533a5"
    end
    on_arm do
      url "https://github.com/Fuabioo/user-top/releases/download/v#{version}/user-top_Darwin_arm64.tar.gz"
      sha256 "e618dce3b245436b23dfa738bc7199d0d9dbe708262e2683422256ce1e2dc78d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Fuabioo/user-top/releases/download/v#{version}/user-top_Linux_amd64.tar.gz"
      sha256 "f78b70fcfaba08340d2913444fe3e328b201d927812c628a8324b464995bcfb3"
    end
    on_arm do
      url "https://github.com/Fuabioo/user-top/releases/download/v#{version}/user-top_Linux_arm64.tar.gz"
      sha256 "3786c7e38bd3386f890d79fdbcad97e7aab27f17d1ec3acbe272b63bc9e9770f"
    end
  end

  # No zap stanza required
end
