# This file was generated by GoReleaser. DO NOT EDIT.
cask "vagrant-top" do
  name "vagrant-top"
  desc "vagrant-top - A TUI for monitoring Vagrant virtual machines."
  homepage "https://github.com/Fuabioo/vagrant-top"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vagrant-top"

  on_macos do
    on_intel do
      url "https://github.com/Fuabioo/vagrant-top/releases/download/v#{version}/vagrant-top_Darwin_amd64.tar.gz"
      sha256 "f521a14282dc1a517a9c7c8f268cbdd4eeb63fc64818db617184ccfbc5448bfe"
    end
    on_arm do
      url "https://github.com/Fuabioo/vagrant-top/releases/download/v#{version}/vagrant-top_Darwin_arm64.tar.gz"
      sha256 "3f21e5912e03d97c1c795c3707fda7a7d3a0bc589ba9b438406e90c666afa7a9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Fuabioo/vagrant-top/releases/download/v#{version}/vagrant-top_Linux_amd64.tar.gz"
      sha256 "a7b46fdf53dfabe4a7dc46298d67f8284b4cb775614e107803c35df06d679639"
    end
    on_arm do
      url "https://github.com/Fuabioo/vagrant-top/releases/download/v#{version}/vagrant-top_Linux_arm64.tar.gz"
      sha256 "84975b726812f1ee52fc601e61e7f510d133271e8f93db4449f234aac8803ce7"
    end
  end

  # No zap stanza required
end
