# This file was generated by GoReleaser. DO NOT EDIT.
cask "vagrant-top" do
  name "vagrant-top"
  desc "vagrant-top - A TUI for monitoring Vagrant virtual machines."
  homepage "https://github.com/Fuabioo/vagrant-top"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vagrant-top"

  on_macos do
    on_intel do
      url "https://github.com/Fuabioo/vagrant-top/releases/download/v#{version}/vagrant-top_Darwin_amd64.tar.gz"
      sha256 "5d97f4b4b9935d4d8aca29b2cd967d5fc964e73fcf822de9e3076dd8beea2384"
    end
    on_arm do
      url "https://github.com/Fuabioo/vagrant-top/releases/download/v#{version}/vagrant-top_Darwin_arm64.tar.gz"
      sha256 "8db6a9bb55cff1e918d0e794b79f835cc1e696e8447b85f20ea66d7b00fd3555"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Fuabioo/vagrant-top/releases/download/v#{version}/vagrant-top_Linux_amd64.tar.gz"
      sha256 "0d568b0fed2fc7f02a6117ce47830e629305f42afda4a39a7e43af45362fb20e"
    end
    on_arm do
      url "https://github.com/Fuabioo/vagrant-top/releases/download/v#{version}/vagrant-top_Linux_arm64.tar.gz"
      sha256 "352e5334a17b58406b35dbaca3fb3a5d960b6574b760df39aa878ee4b18a2798"
    end
  end

  # No zap stanza required
end
