# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Coc < Formula
  desc "CMD Output Curator — curate CLI output for AI agents"
  homepage "https://github.com/Fuabioo/coc"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Fuabioo/cmd-output-curator/releases/download/v0.1.1/coc_Darwin_amd64.tar.gz"
      sha256 "78017b1850f1337a3acf9518b5b6ff0c733454f5e98b39795c96023c9e0a005d"

      def install
        bin.install "coc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Fuabioo/cmd-output-curator/releases/download/v0.1.1/coc_Darwin_arm64.tar.gz"
      sha256 "529167f2271981624a7fb85ae18dd59d0b5d2d10570f0deea77cc1decf17925c"

      def install
        bin.install "coc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fuabioo/cmd-output-curator/releases/download/v0.1.1/coc_Linux_amd64.tar.gz"
      sha256 "15068ff42dafc4f63e064b5605fc87f9d8c58b9565d9f0fabbd21ed56aa7bdcb"
      def install
        bin.install "coc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fuabioo/cmd-output-curator/releases/download/v0.1.1/coc_Linux_arm64.tar.gz"
      sha256 "37f956af79fbe902dadcb4923fdf17f22125c937dfa3bcc9e0b7757115c0c49e"
      def install
        bin.install "coc"
      end
    end
  end

  test do
    system "#{bin}/coc", "--version"
  end
end
