# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Coc < Formula
  desc "CMD Output Curator — curate CLI output for AI agents"
  homepage "https://github.com/Fuabioo/coc"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Fuabioo/cmd-output-curator/releases/download/v0.1.0/coc_Darwin_amd64.tar.gz"
      sha256 "21fcb302fd526e136c5662d6770b87c7399b6158325fb3bd47252eb9192cd9a1"

      def install
        bin.install "coc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Fuabioo/cmd-output-curator/releases/download/v0.1.0/coc_Darwin_arm64.tar.gz"
      sha256 "3d1d10daa73fa798fe5964304c69ba3ffb7d0831f97a15e59aa0b520d69e1f08"

      def install
        bin.install "coc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fuabioo/cmd-output-curator/releases/download/v0.1.0/coc_Linux_amd64.tar.gz"
      sha256 "7cb6fd6ebe9fb12b12df1052ddf68826039ac49224622a7d0eb8381317a8df81"
      def install
        bin.install "coc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fuabioo/cmd-output-curator/releases/download/v0.1.0/coc_Linux_arm64.tar.gz"
      sha256 "f5d3f3bec72565ed25edd8bc0ec0143d21a65cfedbc45efd764212e857f469d0"
      def install
        bin.install "coc"
      end
    end
  end

  test do
    system "#{bin}/coc", "version"
  end
end
