# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevHud < Formula
  desc "Transparent Wayland overlay HUD for monitoring Claude Code sessions"
  homepage "https://github.com/Fuabioo/dev-hud"
  version "0.1.1"
  license "MIT"

  depends_on "wayland" => :optional
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/Fuabioo/dev-hud/releases/download/v0.1.1/dev-hud_0.1.1_linux_amd64.tar.gz"
    sha256 "dd8e0a37a4379cd230ca8cd2d450af04b1c89a016055067a059b2e85f286251b"
    define_method(:install) do
      bin.install "dev-hud"
      bin.install "dev-hud-ctl"
      # Install service file template — user must configure DEV_HUD_SCREEN
      (pkgshare/"service").install "dev-hud.service"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/Fuabioo/dev-hud/releases/download/v0.1.1/dev-hud_0.1.1_linux_arm64.tar.gz"
    sha256 "2107223d1cb238a544b6c783eda5cba4d640ae5d7e139dbadde476ab480e6819"
    define_method(:install) do
      bin.install "dev-hud"
      bin.install "dev-hud-ctl"
      # Install service file template — user must configure DEV_HUD_SCREEN
      (pkgshare/"service").install "dev-hud.service"
    end
  end

  def caveats
    <<~EOS
      To run dev-hud as a systemd user service:

        # 1. Install the service file
        mkdir -p ~/.config/systemd/user
        sed "s|ExecStart=.*|ExecStart=#{opt_bin}/dev-hud|" \
          #{opt_pkgshare}/service/dev-hud.service \
          > ~/.config/systemd/user/dev-hud.service

        # 2. Set your monitor (replace DP-2 with your output name)
        #    Find outputs with: cosmic-randr list || wlr-randr
        sed -i 's/DEV_HUD_SCREEN=.*/DEV_HUD_SCREEN=YOUR_MONITOR/' \
          ~/.config/systemd/user/dev-hud.service

        # 3. Enable and start
        systemctl --user daemon-reload
        systemctl --user enable --now dev-hud.service

      Shell widgets config (optional): ~/.config/viz/shells.md
    EOS
  end

  test do
    assert_match "dev-hud-ctl", shell_output("#{bin}/dev-hud-ctl 2>&1", 1)
  end
end
