# typed: false
# frozen_string_literal: true

# This formula is auto-generated by GoReleaser on releases
# Manual updates will be overwritten by the next release
class Forjamundos < Formula
  desc "Declarative environment setup tool for development tools"
  homepage "https://github.com/Fuabioo/forjamundos"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Fuabioo/forjamundos/releases/download/v0.1.0/forjamundos_Darwin_arm64.tar.gz"
      sha256 "c4f69883f1df0f81dcbd6c1f1519b40ddd1f68d916fad46de3f23b6cbdb5e7b2"
    else
      url "https://github.com/Fuabioo/forjamundos/releases/download/v0.1.0/forjamundos_Darwin_amd64.tar.gz"
      sha256 "804230b3b5c3d0901aac47a051e70baa1207eeb143498fe45b9f26a1c82b0a69"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Fuabioo/forjamundos/releases/download/v0.1.0/forjamundos_Linux_arm64.tar.gz"
      sha256 "5ce15cbef23d1c7e14d4f83d5e120c09ea78c19535157d47400f4ccb8646c4c5"
    else
      url "https://github.com/Fuabioo/forjamundos/releases/download/v0.1.0/forjamundos_Linux_amd64.tar.gz"
      sha256 "8639a2669c6077c04415fe03d915e1b51a7d505b57cd673ac7bc9f21a1bc56ea"
    end
  end

  def install
    bin.install "forjamundos"

    # Install example configuration
    (share/"forjamundos").install "examples/forjamundos.yaml" if File.exist?("examples/forjamundos.yaml")

    # Generate man page if available
    (man1/"forjamundos.1").write Utils.safe_popen_read(bin/"forjamundos", "man") if File.exist?(bin/"forjamundos")

    # Generate shell completions
    generate_completions_from_executable(bin/"forjamundos", "completion")
  end

  test do
    # Test that the binary runs
    assert_match "forjamundos version #{version}", shell_output("#{bin}/forjamundos version")

    # Test config generation
    assert_match "version:", shell_output("#{bin}/forjamundos config generate")

    # Test doctor command (non-destructive)
    system "#{bin}/forjamundos", "doctor"
  end

  def caveats
    <<~EOS
      Example configuration installed to:
        #{share}/forjamundos/forjamundos.yaml

      To get started:
        1. Copy the example config to your home directory:
           cp #{share}/forjamundos/forjamundos.yaml ~/.forjamundos.yaml

        2. Edit the configuration to match your needs:
           $EDITOR ~/.forjamundos.yaml

        3. Run the doctor command to check your system:
           forjamundos doctor

        4. Install packages (dry-run first):
           forjamundos install --dry-run
           forjamundos install

      For more information:
        forjamundos --help
    EOS
  end
end
