# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HookChain < Formula
  desc "Sequential Hook Executor — chain multiple hooks for Claude Code"
  homepage "https://github.com/Fuabioo/hook-chain"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Fuabioo/hook-chain/releases/download/v0.1.0/hook-chain_Darwin_amd64.tar.gz"
      sha256 "e073f6a3917fbdb4793b1fd81b79ca2aab62074dbc51b06bffcbd9ca13456e8f"

      def install
        bin.install "hook-chain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Fuabioo/hook-chain/releases/download/v0.1.0/hook-chain_Darwin_arm64.tar.gz"
      sha256 "2144451ddb51a67caa94cf2514151e874770169412c203ec62c9b8ca32377dd6"

      def install
        bin.install "hook-chain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fuabioo/hook-chain/releases/download/v0.1.0/hook-chain_Linux_amd64.tar.gz"
      sha256 "31dd412ae34e4b22a0d05f9c0e9cb1e7665dd7aaeb7f9297cde1e0158665dc97"
      def install
        bin.install "hook-chain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fuabioo/hook-chain/releases/download/v0.1.0/hook-chain_Linux_arm64.tar.gz"
      sha256 "38fe2b698a791ec2edfaa843e9653ead4b33479bca6dcec9174b8ab5a5306bad"
      def install
        bin.install "hook-chain"
      end
    end
  end

  test do
    system "#{bin}/hook-chain", "version"
  end
end
