# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WispDesktop < Formula
  desc "COSMIC-native desktop GUI for the wisp terminal daemon"
  homepage "https://github.com/Fuabioo/wisp"
  version "0.1.3"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/Fuabioo/wisp/releases/download/v0.1.3/wisp-desktop_0.1.3_linux_amd64.tar.gz"
    sha256 "c46a9f9eb451b01b49ec9c44a951ea20fcdd768eacc5a22f9c6c1c01dfee40ce"
    define_method(:install) do
      bin.install "wisp-desktop"
      (share/"icons/hicolor/scalable/apps").install "assets/logo-wisp.svg" => "dev.fabiomora.WispAdmin.svg"
    end
  end

  def post_install
    # Write desktop entry with correct PATH so wisp-desktop can find `wisp`
    desktop = share/"applications/dev.fabiomora.WispAdmin.desktop"
    desktop.write <<~DESKTOP
      [Desktop Entry]
      Name=Wisp Desktop
      GenericName=Shared Terminal Manager
      Comment=Manage wisp PTY sessions and attached peers
      Exec=env PATH=#{HOMEBREW_PREFIX}/bin:#{ENV["PATH"]} wisp-desktop
      Icon=dev.fabiomora.WispAdmin
      Type=Application
      Terminal=false
      Categories=Utility;System;TerminalEmulator;
      Keywords=wisp;ssh;pty;terminal;session;
      StartupNotify=true
      StartupWMClass=dev.fabiomora.WispAdmin
    DESKTOP

    user_apps = File.expand_path("~/.local/share/applications")
    user_icons = File.expand_path("~/.local/share/icons/hicolor/scalable/apps")
    mkdir_p user_apps
    mkdir_p user_icons
    ln_sf desktop, "#{user_apps}/dev.fabiomora.WispAdmin.desktop"
    ln_sf share/"icons/hicolor/scalable/apps/dev.fabiomora.WispAdmin.svg", "#{user_icons}/dev.fabiomora.WispAdmin.svg"
    system "gtk-update-icon-cache", "-f", "-t", File.expand_path("~/.local/share/icons/hicolor") if File.exist?("/usr/bin/gtk-update-icon-cache")
  end

  def caveats
    <<~EOS
      Wisp Desktop is a COSMIC-native desktop app.

      To launch:
        wisp-desktop

      Requires the wisp daemon to be running:
        brew services start wisp
    EOS
  end
end
