# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wisp < Formula
  desc "Lightweight daemon for spawning and sharing PTY-backed terminal sessions over SSH"
  homepage "https://github.com/Fuabioo/wisp"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Fuabioo/wisp/releases/download/v0.1.3/wisp_0.1.3_macos_amd64.tar.gz"
      sha256 "76bd4ececd847539c36d6e5de99dd1a936d2664ba24f453b777e3ee228dd15ad"

      define_method(:install) do
        bin.install "wisp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Fuabioo/wisp/releases/download/v0.1.3/wisp_0.1.3_macos_arm64.tar.gz"
      sha256 "b9afcd1464cb1228f753d85e98dcb6c2367f23ea041546fd0a1eb496fad3b7ee"

      define_method(:install) do
        bin.install "wisp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fuabioo/wisp/releases/download/v0.1.3/wisp_0.1.3_linux_amd64.tar.gz"
      sha256 "15192f006646cb52cba5e1daf23b239bd9085dd00791e90248c46d747d161a2f"
      define_method(:install) do
        bin.install "wisp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fuabioo/wisp/releases/download/v0.1.3/wisp_0.1.3_linux_arm64.tar.gz"
      sha256 "c9ab0adf091bb7e177dab45f5c5fd08541f6cb896d5daa4d89819d097afba4c1"
      define_method(:install) do
        bin.install "wisp"
      end
    end
  end

  def post_install
    # Install user-level systemd service
    mkdir_p etc/"systemd/user"
    systemd_service = etc/"systemd/user/wisp.service"
    systemd_service.write <<~EOS
      [Unit]
      Description=Wisp Terminal Daemon
      After=network.target

      [Service]
      Type=simple
      ExecStart=#{opt_bin}/wisp daemon
      Restart=on-failure

      [Install]
      WantedBy=default.target
    EOS
  end

  def caveats
    <<~EOS
      To start the daemon now and on login:
        brew services start wisp

      To start a shared terminal session:
        wisp server --port 8082

      To connect to the session:
        ssh -p 8082 localhost
    EOS
  end

  service do
    run [opt_bin/"wisp", "daemon"]
    keep_alive true
    run_type :immediate
    environment_variables PATH: std_service_path_env
    log_path var/"log/wisp.log"
    error_log_path var/"log/wisp.log"
  end
end
