# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xlq < Formula
  desc "xlq - jq for Excel. Streaming xlsx CLI and MCP server."
  homepage "https://github.com/Fuabioo/xlq"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Fuabioo/xlq/releases/download/v1.0.2/xlq_Darwin_amd64.tar.gz"
      sha256 "6965e539bf5e7c52200de41716863c1d9ebdb9eae7dcd867f19ced4cebf0c3c2"

      def install
        bin.install "xlq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Fuabioo/xlq/releases/download/v1.0.2/xlq_Darwin_arm64.tar.gz"
      sha256 "77a3ef2dbb0158716b38aaac64022007bf2c00db9c804e27f21e9fd7849e98c9"

      def install
        bin.install "xlq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fuabioo/xlq/releases/download/v1.0.2/xlq_Linux_amd64.tar.gz"
      sha256 "0d3e927ced1ab5db19be427b95bd9121ca4d3efa2db0f25105936f270ebec8f0"
      def install
        bin.install "xlq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fuabioo/xlq/releases/download/v1.0.2/xlq_Linux_arm64.tar.gz"
      sha256 "f711fcb21e2d828a9ab92d9066cd9bc8d3237a3ecb0c641384028e87dca548b9"
      def install
        bin.install "xlq"
      end
    end
  end

  test do
    system "#{bin}/xlq --version"
  end
end
