# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xlq < Formula
  desc "xlq - jq for Excel. Streaming xlsx CLI and MCP server."
  homepage "https://github.com/Fuabioo/xlq"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Fuabioo/xlq/releases/download/v1.0.3/xlq_Darwin_amd64.tar.gz"
      sha256 "61c0089da13973f1b788b3c2d9e0f8e8e10ab838b1204a171ac414ce7d02ad00"

      def install
        bin.install "xlq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Fuabioo/xlq/releases/download/v1.0.3/xlq_Darwin_arm64.tar.gz"
      sha256 "d36f4c50581e905ba6b379e9bf7ddf07fae2c647fef60ab1d6093b5348f9aa26"

      def install
        bin.install "xlq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fuabioo/xlq/releases/download/v1.0.3/xlq_Linux_amd64.tar.gz"
      sha256 "c358514a6ead106636f669a34c0dc679203ccdd8fa5df44a638e40b726e8db97"
      def install
        bin.install "xlq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fuabioo/xlq/releases/download/v1.0.3/xlq_Linux_arm64.tar.gz"
      sha256 "1723346b48efb8cab9631de581d9ee6cf595dc050a54d0e91626b73d2f7fb264"
      def install
        bin.install "xlq"
      end
    end
  end

  test do
    system "#{bin}/xlq --version"
  end
end
