# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zipfs < Formula
  desc "zipfs - Ephemeral workspace manager for zip files. CLI and MCP server."
  homepage "https://github.com/Fuabioo/zipfs"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Fuabioo/zipfs/releases/download/v0.2.0/zipfs_Darwin_amd64.tar.gz"
      sha256 "2b72a1f2cdec91fedfea2cf008b3c3c08587e9534cbfe4a009db90937c33eeaf"

      def install
        bin.install "zipfs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Fuabioo/zipfs/releases/download/v0.2.0/zipfs_Darwin_arm64.tar.gz"
      sha256 "9c3505061495b35bd11019e715e6327342bb74d9f50472995559d73927798b2f"

      def install
        bin.install "zipfs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fuabioo/zipfs/releases/download/v0.2.0/zipfs_Linux_amd64.tar.gz"
      sha256 "1edf30f6949132bb3734416fc8cac15a933fc722691e68014124c3b762ba88ae"
      def install
        bin.install "zipfs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fuabioo/zipfs/releases/download/v0.2.0/zipfs_Linux_arm64.tar.gz"
      sha256 "6650a7e324dcfb5565db9133965764f2f9a76b68fc59e637d2d037c09e835db3"
      def install
        bin.install "zipfs"
      end
    end
  end

  test do
    system "#{bin}/zipfs --version"
  end
end
