# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zipfs < Formula
  desc "zipfs - Ephemeral workspace manager for zip files. CLI and MCP server."
  homepage "https://github.com/Fuabioo/zipfs"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Fuabioo/zipfs/releases/download/v0.1.0/zipfs_Darwin_amd64.tar.gz"
      sha256 "71b75ae6905d8d44bd2347315efaebd8b7976839880b9173dbc87f5c53aeb969"

      def install
        bin.install "zipfs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Fuabioo/zipfs/releases/download/v0.1.0/zipfs_Darwin_arm64.tar.gz"
      sha256 "ed37546d6fded04d13560853dbcbecc93310319cb8d72ed07ca048f19fd91dcd"

      def install
        bin.install "zipfs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fuabioo/zipfs/releases/download/v0.1.0/zipfs_Linux_amd64.tar.gz"
      sha256 "5a8e2cc274b4957f1de2e439e635374afda28b17c95eced54ec6901c5b54074f"
      def install
        bin.install "zipfs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fuabioo/zipfs/releases/download/v0.1.0/zipfs_Linux_arm64.tar.gz"
      sha256 "d0e7257b958a4a2e8a545e64cace6ef8e3a1d35845225700593eb36033176e75"
      def install
        bin.install "zipfs"
      end
    end
  end

  test do
    system "#{bin}/zipfs --version"
  end
end
